#!/bin/bash
# Build script for streamscraper
# Edit target platforms in build-targets-list.txt
# (one target per line)

rm -rf bin

for word in $(cat build-targets-list.txt)
do
   dotnet publish -c Release --runtime $word
done

cd bin/Release/netcoreapp2.2
mkdir ../packed

for D in */
do
   tar czf "../packed/${D%?}.tar.gz" "$D"publish
done;
